# ANN For Regression Model

## Introduction
An Artificial Neural Network (ANN) is a model inspired by how the human brain learns.
In regression problems, it predicts continuous values instead of categories.
Example:

Predicting insurance charges 💰

Predicting temperature 🌡️

Predicting exam scores

## Introduction

An Artificial Neural Network (ANN) is a model inspired by how the human brain learns.
In regression problems, it predicts continuous values instead of categories.
Example:

1.Predicting insurance charges

2.Predicting temperature

3.Predicting exam scores

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [1]:
# BASIC CHECKS

In [4]:
df = pd.read_csv("insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

# OHE (ONE HOT ENCODING)

In [5]:
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [6]:
region_encoded = pd.get_dummies(df["region"], prefix="region", drop_first=True)
df = pd.concat([df, region_encoded], axis=1)
df.drop("region", axis=1, inplace=True)

In [7]:
df

,age,sex,bmi,children,smoker,charges,region_northwest,region_southeast,region_southwest
0,19,female,27.900,0,yes,16884.92400,False,False,True
1,18,male,33.770,1,no,1725.55230,False,True,False
2,28,male,33.000,3,no,4449.46200,False,True,False
3,33,male,22.705,0,no,21984.47061,True,False,False
4,32,male,28.880,0,no,3866.85520,True,False,False
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,10600.54830,True,False,False
1334,18,female,31.920,0,no,2205.98080,False,False,False
1335,18,female,36.850,0,no,1629.83350,False,True,False
1336,21,female,25.800,0,no,2007.94500,False,False,True
1337,61,female,29.070,0,yes,29141.36030,True,False,False

In [ ]:
# LABEL ENCODING

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])
df['smoker'] = le.fit_transform(df['smoker'])

In [9]:
df

,age,sex,bmi,children,smoker,charges,region_northwest,region_southeast,region_southwest
0,19,0,27.900,0,1,16884.92400,False,False,True
1,18,1,33.770,1,0,1725.55230,False,True,False
2,28,1,33.000,3,0,4449.46200,False,True,False
3,33,1,22.705,0,0,21984.47061,True,False,False
4,32,1,28.880,0,0,3866.85520,True,False,False
...,...,...,...,...,...,...,...,...,...
1333,50,1,30.970,3,0,10600.54830,True,False,False
1334,18,0,31.920,0,0,2205.98080,False,False,False
1335,18,0,36.850,0,0,1629.83350,False,True,False
1336,21,0,25.800,0,0,2007.94500,False,False,True
1337,61,0,29.070,0,1,29141.36030,True,False,False

In [12]:
X = df.drop('charges', axis=1)
y = df['charges']

In [13]:
X

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest
0,19,0,27.900,0,1,False,False,True
1,18,1,33.770,1,0,False,True,False
2,28,1,33.000,3,0,False,True,False
3,33,1,22.705,0,0,True,False,False
4,32,1,28.880,0,0,True,False,False
...,...,...,...,...,...,...,...,...
1333,50,1,30.970,3,0,True,False,False
1334,18,0,31.920,0,0,False,False,False
1335,18,0,36.850,0,0,False,True,False
1336,21,0,25.800,0,0,False,False,True
1337,61,0,29.070,0,1,True,False,False

In [14]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
X_train

array([[ 0.47222651, -1.0246016 , -1.75652513, ...,  1.78316783,
        -0.59966106, -0.5723141 ],
       [ 0.54331294, -1.0246016 , -1.03308239, ..., -0.56079971,
        -0.59966106, -0.5723141 ],
       [ 0.8987451 , -1.0246016 , -0.94368672, ..., -0.56079971,
         1.66760869, -0.5723141 ],
       ...,
       [ 1.3252637 ,  0.97598911, -0.89153925, ..., -0.56079971,
        -0.59966106, -0.5723141 ],
       [-0.16755139, -1.0246016 ,  2.82086429, ..., -0.56079971,
        -0.59966106,  1.74729228],
       [ 1.1120044 ,  0.97598911, -0.10932713, ..., -0.56079971,
        -0.59966106,  1.74729228]])

In [23]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer (no activation for regression)
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [24]:
model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='mse',          # Mean Squared Error for regression
    metrics=['mae']       # Mean Absolute Error as an additional metric
)

In [25]:
history = model.fit(X_train, y_train, epochs=100, validation_split=0.2)

Epoch 1/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 371854688.0000 - mae: 14357.7051 - val_loss: 310308288.0000 - val_mae: 12653.3555
Epoch 2/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 312593600.0000 - mae: 13351.6289 - val_loss: 310183104.0000 - val_mae: 12649.0361
Epoch 3/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 322336032.0000 - mae: 13178.8887 - val_loss: 309913152.0000 - val_mae: 12640.3682
Epoch 4/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 327476352.0000 - mae: 13506.8721 - val_loss: 309379808.0000 - val_mae: 12624.1465
Epoch 5/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 321930080.0000 - mae: 13419.9209 - val_loss: 308474016.0000 - val_mae: 12597.5703
Epoch 6/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 353012416.0000 - mae: 14205.6572 - val_loss: 307025376.0000 - val_mae: 12556.6094
Epoch 7/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 322831744.0000 - mae: 13407.8203 - val_loss: 304938816.0000 - val_mae: 12498.8906
Epoch 8/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 335385152.0000 - mae: 13663.6055 - val_loss: 301994400.0000 - val_mae: 12419.0703
Epoch 9/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 301289280.0000 - mae: 13071.7080 - val_loss: 298234752.0000 - val_mae: 12317.6826
Epoch 10/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 302861600.0000 - mae: 12932.5479 - val_loss: 293423776.0000 - val_mae: 12189.1777
Epoch 11/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 323420896.0000 - mae: 13337.1299 - val_loss: 287535168.0000 - val_mae: 12032.0898
Epoch 12/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 277168256.0000 - mae: 12468.0098 - val_loss: 280561728.0000 - val_mae: 11844.5840
Epoch 13/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 278678752.0000 - mae: 12328.7197 - val_loss: 272577984.0000 - val_mae: 11627.7285
Epoch 14/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 242095344.0000 - mae: 11508.2617 - val_loss: 263241760.0000 - val_mae: 11373.1982
Epoch 15/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 284209152.0000 - mae: 12383.3398 - val_loss: 252653360.0000 - val_mae: 11078.6680
Epoch 16/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 284125728.0000 - mae: 12385.5225 - val_loss: 241276336.0000 - val_mae: 10757.3281
Epoch 17/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 253499616.0000 - mae: 11535.0381 - val_loss: 228955024.0000 - val_mae: 10400.3770
Epoch 18/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 230829728.0000 - mae: 10996.4414 - val_loss: 216193488.0000 - val_mae: 10020.8936
Epoch 19/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 232448112.0000 - mae: 10795.4307 - val_loss: 202140336.0000 - val_mae: 9600.3154
Epoch 20/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 231967296.0000 - mae: 10735.8184 - val_loss: 188298080.0000 - val_mae: 9175.6631
Epoch 21/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 204112704.0000 - mae: 10040.9150 - val_loss: 173984320.0000 - val_mae: 8724.3105
Epoch 22/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 165267568.0000 - mae: 8955.4014 - val_loss: 160552288.0000 - val_mae: 8291.3447
Epoch 23/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 166895872.0000 - mae: 8859.7930 - val_loss: 147055600.0000 - val_mae: 7858.6138
Epoch 24/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 141830560.0000 - mae: 8176.2822 - val_loss: 133340832.0000 - val_mae: 7409.0298
Epoch 25/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 136512048.0000 - mae: 7911.4448 - val_loss: 121133608.0000 - val_mae: 6986.3701
Epoch 26/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 133434264.0000 - mae: 7664.5215 - val_loss: 109264160.0000 - val_mae: 6566.5034
Epoch 27/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 120727896.0000 - mae: 7093.9536 - val_loss: 99273552.0000 - val_mae: 6202.3535
Epoch 28/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 92857440.0000 - mae: 6337.2964 - val_loss: 89814360.0000 - val_mae: 5853.3076
Epoch 29/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 100842296.0000 - mae: 6631.4336 - val_loss: 81063632.0000 - val_mae: 5529.8657
Epoch 30/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 83306128.0000 - mae: 5988.1367 - val_loss: 73758032.0000 - val_mae: 5254.4492
Epoch 31/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 73577600.0000 - mae: 5501.6084 - val_loss: 67399712.0000 - val_mae: 5003.8203
Epoch 32/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 70503872.0000 - mae: 5404.6694 - val_loss: 62027280.0000 - val_mae: 4798.2197
Epoch 33/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 59854944.0000 - mae: 4997.1030 - val_loss: 57386476.0000 - val_mae: 4647.6914
Epoch 34/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 51123340.0000 - mae: 4602.0903 - val_loss: 53406920.0000 - val_mae: 4540.6777
Epoch 35/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 51942400.0000 - mae: 4794.7002 - val_loss: 50210004.0000 - val_mae: 4444.4590
Epoch 36/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 53971228.0000 - mae: 4913.5356 - val_loss: 47460684.0000 - val_mae: 4378.5190
Epoch 37/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 51432704.0000 - mae: 4660.5259 - val_loss: 45263412.0000 - val_mae: 4321.1655
Epoch 38/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 50767612.0000 - mae: 4627.3252 - val_loss: 43476904.0000 - val_mae: 4286.7119
Epoch 39/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 43099660.0000 - mae: 4431.2817 - val_loss: 41931152.0000 - val_mae: 4258.4414
Epoch 40/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 42153396.0000 - mae: 4548.4976 - val_loss: 40635504.0000 - val_mae: 4241.3003
Epoch 41/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 42924324.0000 - mae: 4552.2461 - val_loss: 39576656.0000 - val_mae: 4220.1387
Epoch 42/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 42918440.0000 - mae: 4574.4639 - val_loss: 38677012.0000 - val_mae: 4202.5244
Epoch 43/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 38974384.0000 - mae: 4308.1284 - val_loss: 38000596.0000 - val_mae: 4180.9502
Epoch 44/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 41229028.0000 - mae: 4494.0620 - val_loss: 37351524.0000 - val_mae: 4159.4639
Epoch 45/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 35307996.0000 - mae: 4247.8247 - val_loss: 36815292.0000 - val_mae: 4135.2627
Epoch 46/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 35896352.0000 - mae: 4208.5244 - val_loss: 36385372.0000 - val_mae: 4116.7031
Epoch 47/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 39761680.0000 - mae: 4389.2798 - val_loss: 35967372.0000 - val_mae: 4095.4082
Epoch 48/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 37497784.0000 - mae: 4347.2593 - val_loss: 35611044.0000 - val_mae: 4079.8298
Epoch 49/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 32456672.0000 - mae: 3991.2046 - val_loss: 35361068.0000 - val_mae: 4059.4653
Epoch 50/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 35006208.0000 - mae: 4167.2227 - val_loss: 35092500.0000 - val_mae: 4045.4795
Epoch 51/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 35202884.0000 - mae: 4244.0903 - val_loss: 34889096.0000 - val_mae: 4025.3875
Epoch 52/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 35693976.0000 - mae: 4187.3843 - val_loss: 34692996.0000 - val_mae: 4009.5222
Epoch 53/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 36589864.0000 - mae: 4260.0981 - val_loss: 34498524.0000 - val_mae: 3995.9380
Epoch 54/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 42799308.0000 - mae: 4520.0435 - val_loss: 34338840.0000 - val_mae: 3983.1846
Epoch 55/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 37695140.0000 - mae: 4364.8081 - val_loss: 34213852.0000 - val_mae: 3967.1636
Epoch 56/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 33749828.0000 - mae: 4102.8174 - val_loss: 34126912.0000 - val_mae: 3955.6968
Epoch 57/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 35420876.0000 - mae: 4298.2222 - val_loss: 33964140.0000 - val_mae: 3943.8901
Epoch 58/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 35281788.0000 - mae: 4189.3301 - val_loss: 33880376.0000 - val_mae: 3929.5615
Epoch 59/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 39430456.0000 - mae: 4376.0571 - val_loss: 33786344.0000 - val_mae: 3923.3254
Epoch 60/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 38232444.0000 - mae: 4340.8999 - val_loss: 33739820.0000 - val_mae: 3914.6057
Epoch 61/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 37231152.0000 - mae: 4234.3252 - val_loss: 33645700.0000 - val_mae: 3904.6284
Epoch 62/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 37845976.0000 - mae: 4215.2656 - val_loss: 33536090.0000 - val_mae: 3898.0554
Epoch 63/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 34871128.0000 - mae: 4037.8093 - val_loss: 33510008.0000 - val_mae: 3883.5278
Epoch 64/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 37608572.0000 - mae: 4261.4937 - val_loss: 33437228.0000 - val_mae: 3881.4661
Epoch 65/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 36768560.0000 - mae: 4139.5698 - val_loss: 33374180.0000 - val_mae: 3870.9595
Epoch 66/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 32158920.0000 - mae: 4026.5596 - val_loss: 33366782.0000 - val_mae: 3864.3149
Epoch 67/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 40918112.0000 - mae: 4336.7603 - val_loss: 33285116.0000 - val_mae: 3858.5232
Epoch 68/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 36656832.0000 - mae: 4121.3247 - val_loss: 33244354.0000 - val_mae: 3858.6323
Epoch 69/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 37475440.0000 - mae: 4139.5229 - val_loss: 33191526.0000 - val_mae: 3848.8762
Epoch 70/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 36743292.0000 - mae: 4185.7549 - val_loss: 33151748.0000 - val_mae: 3845.0928
Epoch 71/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 32648630.0000 - mae: 4007.1499 - val_loss: 33099898.0000 - val_mae: 3840.3789
Epoch 72/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 36149948.0000 - mae: 4086.1370 - val_loss: 33095880.0000 - val_mae: 3832.4673
Epoch 73/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 37232136.0000 - mae: 4148.9746 - val_loss: 33050590.0000 - val_mae: 3830.3247
Epoch 74/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 36891264.0000 - mae: 4161.2871 - val_loss: 32980988.0000 - val_mae: 3824.9294
Epoch 75/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 31887204.0000 - mae: 3855.7039 - val_loss: 33009464.0000 - val_mae: 3816.5671
Epoch 76/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 39936012.0000 - mae: 4236.5723 - val_loss: 32951940.0000 - val_mae: 3814.3054
Epoch 77/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 34600896.0000 - mae: 4053.4900 - val_loss: 32947222.0000 - val_mae: 3813.5884
Epoch 78/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 32880868.0000 - mae: 3986.3801 - val_loss: 32893942.0000 - val_mae: 3808.1396
Epoch 79/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 33091570.0000 - mae: 3994.2246 - val_loss: 32872940.0000 - val_mae: 3805.6746
Epoch 80/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 35538272.0000 - mae: 4109.5103 - val_loss: 32818370.0000 - val_mae: 3802.0176
Epoch 81/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 38022156.0000 - mae: 4175.7075 - val_loss: 32813912.0000 - val_mae: 3800.0835
Epoch 82/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 33625348.0000 - mae: 3935.2949 - val_loss: 32764944.0000 - val_mae: 3796.3213
Epoch 83/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 34842504.0000 - mae: 3969.8638 - val_loss: 32762322.0000 - val_mae: 3796.4817
Epoch 84/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 35683896.0000 - mae: 4086.5098 - val_loss: 32758606.0000 - val_mae: 3789.9702
Epoch 85/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 33711768.0000 - mae: 4037.2002 - val_loss: 32754338.0000 - val_mae: 3787.1951
Epoch 86/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 36129008.0000 - mae: 4109.8940 - val_loss: 32703008.0000 - val_mae: 3785.1597
Epoch 87/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 35410804.0000 - mae: 4060.9758 - val_loss: 32676746.0000 - val_mae: 3784.7415
Epoch 88/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 37072616.0000 - mae: 4108.0952 - val_loss: 32668462.0000 - val_mae: 3782.7756
Epoch 89/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 34328716.0000 - mae: 4041.9619 - val_loss: 32640168.0000 - val_mae: 3777.4592
Epoch 90/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 33467966.0000 - mae: 4020.1956 - val_loss: 32611414.0000 - val_mae: 3775.3916
Epoch 91/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 33250624.0000 - mae: 3925.6292 - val_loss: 32550976.0000 - val_mae: 3775.0537
Epoch 92/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 35227356.0000 - mae: 4068.3728 - val_loss: 32556092.0000 - val_mae: 3773.5835
Epoch 93/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 35032736.0000 - mae: 3960.6160 - val_loss: 32552286.0000 - val_mae: 3768.5293
Epoch 94/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 36956976.0000 - mae: 4166.8242 - val_loss: 32496008.0000 - val_mae: 3766.8655
Epoch 95/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 38908976.0000 - mae: 4177.6021 - val_loss: 32507060.0000 - val_mae: 3765.4053
Epoch 96/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 34356696.0000 - mae: 4042.2463 - val_loss: 32507734.0000 - val_mae: 3764.6372
Epoch 97/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 31637196.0000 - mae: 3839.7712 - val_loss: 32441712.0000 - val_mae: 3764.1519
Epoch 98/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 32110544.0000 - mae: 3843.5376 - val_loss: 32442278.0000 - val_mae: 3758.6404
Epoch 99/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 35616256.0000 - mae: 4002.9841 - val_loss: 32442542.0000 - val_mae: 3760.9072
Epoch 100/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 38210632.0000 - mae: 4184.0664 - val_loss: 32396442.0000 - val_mae: 3760.1218
Epoch 101/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 32132640.0000 - mae: 3875.3315 - val_loss: 32411342.0000 - val_mae: 3755.7649
Epoch 102/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 30994112.0000 - mae: 3765.2683 - val_loss: 32367174.0000 - val_mae: 3751.6821
Epoch 103/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 31690878.0000 - mae: 3860.6951 - val_loss: 32378184.0000 - val_mae: 3751.9202
Epoch 104/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 36544320.0000 - mae: 4118.5459 - val_loss: 32343126.0000 - val_mae: 3750.7874
Epoch 105/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 31836840.0000 - mae: 3819.9785 - val_loss: 32316736.0000 - val_mae: 3747.5725
Epoch 106/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 32319526.0000 - mae: 3829.4924 - val_loss: 32269612.0000 - val_mae: 3748.2869
Epoch 107/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 34861180.0000 - mae: 3999.9849 - val_loss: 32251758.0000 - val_mae: 3748.7769
Epoch 108/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 32343230.0000 - mae: 3924.8862 - val_loss: 32240716.0000 - val_mae: 3744.2891
Epoch 109/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 33596512.0000 - mae: 3975.6865 - val_loss: 32235594.0000 - val_mae: 3738.2607
Epoch 110/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 37186504.0000 - mae: 4145.3130 - val_loss: 32224650.0000 - val_mae: 3743.8528
Epoch 111/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 39439240.0000 - mae: 4141.9316 - val_loss: 32187904.0000 - val_mae: 3739.4719
Epoch 112/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 35074780.0000 - mae: 4083.8958 - val_loss: 32197744.0000 - val_mae: 3736.4038
Epoch 113/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 32153494.0000 - mae: 3817.2224 - val_loss: 32174502.0000 - val_mae: 3735.4226
Epoch 114/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 33599044.0000 - mae: 3938.0715 - val_loss: 32138494.0000 - val_mae: 3735.1709
Epoch 115/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 34234476.0000 - mae: 4020.0774 - val_loss: 32144630.0000 - val_mae: 3731.2568
Epoch 116/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 33441820.0000 - mae: 3924.7671 - val_loss: 32114774.0000 - val_mae: 3728.6873
Epoch 117/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 34487296.0000 - mae: 4025.9656 - val_loss: 32119248.0000 - val_mae: 3729.5088
Epoch 118/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 33560704.0000 - mae: 4023.8711 - val_loss: 32099142.0000 - val_mae: 3727.8499
Epoch 119/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 36779688.0000 - mae: 4060.2632 - val_loss: 32036258.0000 - val_mae: 3727.8193
Epoch 120/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 33876904.0000 - mae: 4004.1875 - val_loss: 32017872.0000 - val_mae: 3724.9729
Epoch 121/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 38250252.0000 - mae: 4036.8967 - val_loss: 32035604.0000 - val_mae: 3719.9641
Epoch 122/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 35101120.0000 - mae: 4065.0071 - val_loss: 32005554.0000 - val_mae: 3719.9470
Epoch 123/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 35028072.0000 - mae: 4036.7734 - val_loss: 32046146.0000 - val_mae: 3718.6848
Epoch 124/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 30870376.0000 - mae: 3774.2178 - val_loss: 31988590.0000 - val_mae: 3718.9617
Epoch 125/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 31401370.0000 - mae: 3861.9001 - val_loss: 31975362.0000 - val_mae: 3712.8914
Epoch 126/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 33057860.0000 - mae: 3985.7478 - val_loss: 31962360.0000 - val_mae: 3713.7756
Epoch 127/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 36649216.0000 - mae: 4107.8882 - val_loss: 31918504.0000 - val_mae: 3712.9258
Epoch 128/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 36928472.0000 - mae: 4129.8188 - val_loss: 31916152.0000 - val_mae: 3711.7734
Epoch 129/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 32233352.0000 - mae: 3964.6687 - val_loss: 31907512.0000 - val_mae: 3710.1636
Epoch 130/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31587618.0000 - mae: 3924.6765 - val_loss: 31885824.0000 - val_mae: 3706.3645
Epoch 131/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 30330294.0000 - mae: 3690.7136 - val_loss: 31846822.0000 - val_mae: 3704.8838
Epoch 132/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 34588988.0000 - mae: 3938.5315 - val_loss: 31856856.0000 - val_mae: 3702.4983
Epoch 133/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 33091338.0000 - mae: 3864.1633 - val_loss: 31775870.0000 - val_mae: 3701.0693
Epoch 134/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 36321632.0000 - mae: 4113.8657 - val_loss: 31833900.0000 - val_mae: 3701.8904
Epoch 135/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31859690.0000 - mae: 3798.7012 - val_loss: 31778112.0000 - val_mae: 3701.6782
Epoch 136/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 32810422.0000 - mae: 3868.7695 - val_loss: 31812584.0000 - val_mae: 3697.3750
Epoch 137/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 33384888.0000 - mae: 3925.8145 - val_loss: 31733768.0000 - val_mae: 3698.5986
Epoch 138/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 31571162.0000 - mae: 3870.7642 - val_loss: 31715108.0000 - val_mae: 3689.6357
Epoch 139/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 33784928.0000 - mae: 3902.0986 - val_loss: 31705760.0000 - val_mae: 3694.1133
Epoch 140/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 34948108.0000 - mae: 3943.7383 - val_loss: 31703286.0000 - val_mae: 3691.2751
Epoch 141/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 30676876.0000 - mae: 3673.4487 - val_loss: 31677572.0000 - val_mae: 3684.2979
Epoch 142/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 36169864.0000 - mae: 4070.7163 - val_loss: 31635020.0000 - val_mae: 3686.2759
Epoch 143/200
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 30236386.0000 - mae: 3756.6023 - val_loss: 31621154.0000 - val_mae: 3683.2544
Epoch 144/200

In [26]:
loss, mae = model.evaluate(X_test, y_test)
print(f"Test MAE: {mae:.2f}")

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 26431676.0000 - mae: 3558.4324
Test MAE: 3730.64

In [27]:
from sklearn.metrics import mean_squared_error

# Get predictions
y_pred = model.predict(X_test)

# Compute MSE
mse = mean_squared_error(y_test, y_pred)
print("Test MSE:", mse)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
Test MSE: 28829155.586053386